import "./back-to-top.js"
import "./accordion.js"
import "./breadcrumb-styling.js"
import "./browser-banner.js"
import "./chatbot.js"
import "./donate-an-hour.js"
import "./donation_form.js"
import "./equal-height-columns.js"
import "./form_accordion.js"
import "./form-progress-bar.js"
import "./highlight-current-page.js"
import "./image-gallery.js"
import "./mobile-navigation.js"
import "./mobile-tables.js"
import "./on-this-page.js"
import "./podcast-player.js"
import "./polyfill-classlist.js"
import "./postcode-lookup.js"
import "./row-bg.js"
import "./search.js"
import "./search-results-count.js"
import "./sponsor-a-puppy.js"
import "./svg-logo.js"
import "./volunteering.js"
import "./vendor/a11y-toggle.js"


// New scripts to address Sitecore specific-issues
import "./form-generate-session.js"